### ISSUE TITLE
Cannot sample types.nonZero

### ISSUE THREAD

**Issue by eventualbuddha** [graue/gentest#1]
This fails when run from a checkout of gentest:

``` js
> gentest.sample(gentest.types.number.nonZero)
GentestError: suchThat: could not find a suitable value
    at repl:1:10
    at REPLServer.self.eval (repl.js:110:21)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.emit (events.js:95:17)
    at Interface._onLine (readline.js:202:10)
    at Interface._line (readline.js:531:8)
```

**Comment by graue** [comment]
Thanks! Off-by-one bug in `gentest.sample`, now fixed.
